Add setup for config, logging, and plugins
spotify/gordon-janitor pull request #1
Opened 2018-01-22 17:19 UTC by econchick

**What this PR does / why we need it**:

This is copy-pasta from gordon core. Rather than create a common package immediately, I chose to hold off to see if the plugin logic will need to be different in some way. Once the janitor is further develop, we can re-evaluate the need for a gordon-common package.

**Which issue(s) this PR fixes**

N/A

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

cc @spotify/alf

2018-01-22 22:17 UTC, matt0bi requested changes
Overall looks good, I had a few naming related nitpicks (eg. gordon -> gordon-janitor).

2018-01-22 22:17 UTC, matt0bi commented on gordon_janitor/main.py
> +        progname='gordon', level=log_level, handlers=log_handlers)
What do you think about changing `progname='gordon'` to `progname='gordon-janitor'` to make the logs more explicit?

2018-01-22 22:17 UTC, matt0bi commented on gordon_janitor/plugins_loader.py
> +Plugins are initialized with any config defined in ``gordon-user.toml``
`gordon-user.toml` and `gordon.toml` should be `gordon-janitor-user.toml` and `gordon-janitor.toml` to be in line with `main.py`.

2018-01-22 22:17 UTC, matt0bi commented on gordon_janitor/plugins_loader.py
> +example, the ``gcp.gpusub`` will not have access to the configuration
Nitpick, but '_the `gcp.gpubsub` will_' should either drop the '_the_' or specify something after the plugin name eg. '_the `gcp.gpubsub` plugin_'. There's also a missing letter in `gcp.gpusub` (if it was supposed to be `gcp.gpubsub`, it not, never mind).

2018-01-22 22:17 UTC, matt0bi commented on gordon_janitor/plugins_loader.py
> +See :doc:`plugins` for details on how to write a plugin for Gordon.
Another nitpick, but should '_plugin for Gordon._' be '_plugin for Gordon-Janitor._'?

2018-01-22 22:17 UTC, matt0bi commented on MANIFEST.in
> +exclude gordon-janitor*.toml
Good idea :+1:

2018-01-22 22:17 UTC, matt0bi commented on gordon_janitor/plugins_loader.py
> +        config (dict): loaded configuration for the Gordon service.
Another word nitpick: `s/Gordon/Gordon-Janitor/` here and in `test_main.py` on line 119 and possibly on line 197 in the Returns part of this docstring ('_activated in gordon config._' -> '_activated in gordon-janitor config._`.

2018-01-25 16:10 UTC, econchick commented
@matt0bi updated - mind taking a quick look?

2018-01-25 22:08 UTC, matt0bi approved these changes

2018-01-25 22:08 UTC, matt0bi commented
🚢

2018-01-25 22:09 UTC, merged